export const reviews = [
  {
    image: 'url_to_image_1',
    name: 'John Doe',
    date: '2023-01-01',
    contents: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    rateValue: 4.5,
  },
  {
    image: 'url_to_image_2',
    name: 'Jane Smith',
    date: '2023-02-15',
    contents: 'A wonderful experience! I highly recommend it.',
    rateValue: 5.0,
  },
  {
    image: 'url_to_image_3',
    name: 'Alice Johnson',
    date: '2023-03-10',
    contents: 'Great product and excellent customer service.',
    rateValue: 4.8,
  },
  {
    image: 'url_to_image_4',
    name: 'Bob Williams',
    date: '2023-04-05',
    contents: 'Easy to use and exactly what I was looking for.',
    rateValue: 4.0,
  },
  {
    image: 'url_to_image_5',
    name: 'Emily Davis',
    date: '2023-05-20',
    contents: 'Fast shipping and top-notch quality.',
    rateValue: 4.7,
  },
  {
    image: 'url_to_image_6',
    name: 'David Brown',
    date: '2023-06-15',
    contents: 'Impressive service. Will buy again.',
    rateValue: 4.9,
  },
  {
    image: 'url_to_image_7',
    name: 'Sophia White',
    date: '2023-07-01',
    contents: 'Satisfied with the purchase. Thank you!',
    rateValue: 4.2,
  },
  {
    image: 'url_to_image_8',
    name: 'Michael Taylor',
    date: '2023-08-10',
    contents: 'Good value for money. Reliable product.',
    rateValue: 3.5,
  },
  {
    image: 'url_to_image_9',
    name: 'Olivia Green',
    date: '2023-09-05',
    contents: 'Efficient and friendly customer support.',
    rateValue: 4.6,
  },
  {
    image: 'url_to_image_10',
    name: 'William Clark',
    date: '2023-10-20',
    contents: 'Highly recommended. Great overall experience.',
    rateValue: 4.8,
  },
];
